### ISSUE TITLE
在手機上不能運行

### ISSUE THREAD

**Issue by zeteticl** [pulipulichen/jieba-js#16]
https://jsfiddle.net/7pd9e0fz/3/

想請教一下, 這段CODE 可以在PC上運行成功, 但在手機上的Chrome Safari 也會顯示script error
請問我可以怎解決, 
因為在寫一個網站, 但手機上會卡在這步.

**Comment by pulipulichen** [comment]
已回覆在Blogger上
https://blog.pulipuli.info/2017/03/jieba-js-online-chinese-analyzer-jieba.html?showComment=1603207639915#c1599314245974315142

後續回覆請以Blogger那篇的留言為主
